---
title: "Untitled"
output: html_document
date: "2024-10-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RCurl)
library(tidyverse)
library(XML)
library(xml2)
library(rvest)
library(readxl)
library(openxlsx)
library(janitor)
```


```{r}
# make folder all in rds for saving data frame

dir.create("../rds/covid",
             showWarnings = TRUE, recursive = FALSE, mode = "0777")
```


```{r}
list.files("../xlsx/covid")
```

```{r}
csv_covid <- list.files("../xlsx/covid")

csv_covid
```
```{r}
file_covid <- c("death", "daily", "inpt", "severe")
```


```{r}
from_covid <- paste0("../xlsx/covid/", csv_covid)

from_covid
```

```{r}
list_covid <- map(from_covid, function(x){ 
  read_csv(x) %>%
    mutate(YMD = str_replace_all(Date, "/", "-")) %>%
    mutate(YMD = as_date(YMD)) %>%
    mutate(YM = yearmonth(YMD)) %>% return()
})
```

```{r}
to_covid <- paste0("../rds/covid/df_", file_covid)

to_covid
```



```{r}
for (i in 1:length(list_covid)){
  saveRDS(list_covid[[i]], to_covid[i] ) 
}
```


# end

```{r}
for (i in 1:length(list_covid)){
  assign(paste0("df_", file_covid[i]), list_covid[[i]] )
}
```




```{r}
xlsx_test_dem <- list.files("../xlsx/test/dem") 

xlsx_test_dem
```

```{r}
xlsx_inj_dem <- list.files("../xlsx/inj/dem") 

xlsx_inj_dem
```

```{r}
xlsx_surg_dem <- list.files("../xlsx/surg/dem") 

xlsx_surg_dem
```

```{r}
for (i in 1:length(xlsx_test_dem)){
  print(getSheetNames(paste0("../xlsx/test/dem/", xlsx_test_dem[i])))
}
```

```{r}
for (i in 1:length(xlsx_inj_dem)){
  print(getSheetNames(paste0("../xlsx/inj/dem/", xlsx_inj_dem[i])))
}
```

```{r}
for (i in 1:length(xlsx_surg_dem)){
  print(getSheetNames(paste0("../xlsx/surg/dem/", xlsx_surg_dem[i])))
}
```

# read regular sheet

```{r}
get_data_dem_reg <- function(xlsx_path){
  
  sheet_name <- getSheetNames(xlsx_path)
  
  sheet_name <- sheet_name[!str_detect(sheet_name, "加算")]
  
  # read excel sheet
  list_df <- map2(xlsx_path,
                  sheet_name,
                  function(x, y) read.xlsx(x,
                                           sheet = y,
                                           startRow = 4,
                                           fillMergedCells = FALSE)) 
  # clean colnames
  new_colnames_1 <- c("CLASS_code", "CLASS_name",
                       "PRO_code", "PRO_name",
                       "POINT", "TOTAL")

  start <- seq(0, 85, 5)
  end <- seq(4, 89, 5)
  
  range <- paste0(start, "_", end)
  range <- c(range, "90_")
  
  new_colnames_2 <- c(paste0("M_", range), paste0("F_", range))
  
  
  new_colnames <- c(new_colnames_1, new_colnames_2)

  
  list_df <- map(list_df,
                 function(x){
                   colnames(x) <- new_colnames
                   return(x)})
  
  # add file name

  list_df <- map(list_df,
                 function(x){
                   x %>% 
                     mutate(FILE = xlsx_path) %>%
                     mutate(FILE = str_extract(FILE, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
                     relocate(FILE, .before = "CLASS_code")  
                 })

  # add sheet name and do one hot coding for sheet
  # "注射薬 外来 (院内)" "注射薬 外来 (院外)" "注射薬 入院"  
  list_df <- map2(list_df, sheet_name,
                 function(x, y){
                   x %>% 
                     mutate(SHEET_jp = y) %>%
                         mutate(SHEET = case_when(
                           str_detect(SHEET_jp, "全体") ~ "all",
                           str_detect(SHEET_jp, "外来")　&
                             !str_detect(SHEET_jp, "加算")~ "outpt",
                           str_detect(SHEET_jp, "外来")　&
                             str_detect(SHEET_jp, "加算")~ "outpt_ex",
                           str_detect(SHEET_jp, "入院") &
                             !str_detect(SHEET_jp, "加算") ~ "inpt",
                           str_detect(SHEET_jp, "入院") &
                             str_detect(SHEET_jp, "加算") ~ "input_ex"))    %>%
                     relocate(SHEET, .after = "FILE")
                   })
  
  # fill missing cells
  
  list_df <- map(list_df,
                 function(x){
                   x %>% 
                     tidyr::fill(starts_with("CLASS_"), .direction = "down") %>%
                     mutate(across(everything(), as.character))
                 })
  
  # process year
  # function for converting year into Western year
  convert_year <- function(x){
  if (str_detect(x, "^H")){
    y <- x %>% str_remove("^H") %>% as.numeric()
    y <- y + 1988
    return(as.character(y))
  }
  else if (str_detect(x, "^R")){
    y <- x %>% str_remove("^R") %>% as.numeric()
    y <- y + 2018
    return(as.character(y))
  }
  else{
    return(x)
  }
}
  
  # get year
  get_year <- function(x, y){
  read.xlsx(x, sheet = y, startRow =1 , colNames = FALSE, rows = 1) %>% 
    rename(DES_jp = "X1") %>%
    mutate(FILE = x) %>%
    mutate(FILE = str_extract(FILE, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
    mutate(DES_jp = str_remove(DES_jp, "　※.+") )  %>%
    mutate(DES_jp = str_remove(DES_jp, "診療年月："))　%>%
    mutate(YEAR_str = str_extract(DES_jp, "[^年]+(?=年)")) %>%
    mutate(YEAR_end = str_extract(DES_jp, "(?<=～)[^年]+(?=年)")) %>%
    mutate(YEAR_str = convert_year(YEAR_str)) %>%
    mutate(YEAR_end = convert_year(YEAR_end))
    }
  
  list_year <- map2(xlsx_path,
                     sheet_name, get_year)
    
  list_df <- map2(list_df, list_year, function(x, y){
    x %>% left_join(y, by = join_by(FILE == FILE))
  })
    
  # combine
  df <- list_df %>% list_rbind()
  
  return(df)
  }
```

```{r}
df_1 <- read.xlsx("../xlsx/test/dem/0000140356.xlsx",
                   sheet= 1,)
```


```{r}
df_ex <- get_data_dem_reg("../xlsx/test/dem/0000140356.xlsx")
```


```{r}
#df_ex_2 <- get_data_dem_12("../xlsx/test/dem/0000177242.xlsx")
```

```{r}
# for each folider, read the first two files, parse , combine and save
# x is the overall folder name (ext inj)
# y is the individual folder (dem prf)

save_df_dem_reg <- function(x, y){
  xlsx <- list.files(paste0("../xlsx/", x, "/", y))
  
  #xlsx <- xlsx[1:2]
  
  from <- paste0("../xlsx/", x, "/", y, "/", xlsx)
  
  df <- map(from, get_data_dem_reg) %>% list_rbind()
  
  # add category
  df <- df %>% 
    mutate(TYPE = x) %>%
    relocate(TYPE, .after = "FILE") %>%
    mutate(CAT = y) %>%
    relocate(CAT, .after = "TYPE")
  
  saveRDS(df, paste0("../rds/", x, "/", y,"/", "df_", x, "_", y, "_reg"))
}
```

```{r}
save_df_dem_reg("test", "dem")
#save_df_dem_12("ext", "dem")
```

```{r}
df_ext_dem_reg <- readRDS("../rds/test/dem/df_test_dem_reg")
```


```{r}
df_ext_dem_reg %>% count(SHEET)
```

```{r}
df_ext_dem_reg %>% count(YEAR_str)
```
```{r}
df_raw_2 <- read.xlsx("../xlsx/test/dem/0000177242.xlsx",
                                           sheet = 2,
                                           startRow = 4,
                                           fillMergedCells = FALSE)
```


```{r}
colnames(df_raw_2) %>% unique()
```
```{r}
df_raw_2_rm <- df_raw_2 %>% clean_names()
```

```{r}
colnames(df_raw_2_rm)
```


```{r}
df_raw_2_rm <- df_raw_2_rm %>% mutate(across(where(is.character), ~ na_if(.x, " ")))
```

```{r}
df_raw_2_rm %>% select( where(function(x) !all(is.na(x))))
```


# add (additional cost)

# to read the file properly, need to remove "addition" sheets in cells 5B, 5C
# (present randomly)
```{r}
get_data_dem_add <- function(xlsx_path){
  
  sheet_name <- getSheetNames(xlsx_path)
  
  sheet_name <- sheet_name[str_detect(sheet_name, "加算")]
  
  # read excel sheet
  list_df <- map2(xlsx_path,
                  sheet_name,
                  function(x, y) read.xlsx(x,
                                           sheet = y,
                                           startRow = 4,
                                           skipEmptyCols = FALSE,
                                           fillMergedCells = FALSE) %>%
                    return())
  
    # clean colnames
  new_colnames_1 <- c("ADD", "x2", "x3",
                       "PRO_code", "PRO_name",
                       "POINT", "PCT", "TOTAL")

  start <- seq(0, 85, 5)
  end <- seq(4, 89, 5)
  
  range <- paste0(start, "_", end)
  range <- c(range, "90_")
  
  new_colnames_2 <- c(paste0("M_", range), paste0("F_", range))
  
  
  new_colnames <- c(new_colnames_1, new_colnames_2)

  # update colnames
  list_df <- map(list_df,
                 function(x){
                   colnames(x) <- new_colnames
                   return(x)})
  

  # remove x2 and x3
  list_df <- map(list_df,
                 function(x){
                   x %>% select(!c(x2, x3)) %>% return()
                 })
  
  # add file name
  list_df <- map(list_df,
                 function(x){
                   x %>% 
                     mutate(FILE = xlsx_path) %>%
                     mutate(FILE = str_extract(FILE, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
                     relocate(FILE, .before = "ADD")  
                 })

  # add sheet name and do one hot coding for sheet
  # "注射薬 外来 (院内)" "注射薬 外来 (院外)" "注射薬 入院"  
  list_df <- map2(list_df, sheet_name,
                 function(x, y){
                   x %>% 
                     mutate(SHEET_jp = y) %>%
                         mutate(SHEET = case_when(
                           str_detect(SHEET_jp, "全体") ~ "all",
                           str_detect(SHEET_jp, "外来")　&
                             !str_detect(SHEET_jp, "加算")~ "outpt",
                           str_detect(SHEET_jp, "外来")　&
                             str_detect(SHEET_jp, "加算")~ "outpt_add",
                           str_detect(SHEET_jp, "入院") &
                             !str_detect(SHEET_jp, "加算") ~ "inpt",
                           str_detect(SHEET_jp, "入院") &
                             str_detect(SHEET_jp, "加算") ~ "input_add"))    %>%
                     relocate(SHEET, .after = "FILE")
                   })
  
  # fill missing cells
  
  list_df <- map(list_df,
                 function(x){
                   x %>% 
                     tidyr::fill(starts_with("ADD"), .direction = "down") %>%
                     mutate(across(everything(), as.character))
                 })
  
    # process year
  # function for converting year into Western year
  convert_year <- function(x){
  if (str_detect(x, "^H")){
    y <- x %>% str_remove("^H") %>% as.numeric()
    y <- y + 1988
    return(as.character(y))
  }
  else if (str_detect(x, "^R")){
    y <- x %>% str_remove("^R") %>% as.numeric()
    y <- y + 2018
    return(as.character(y))
  }
  else{
    return(x)
  }
}
  
  # get year
  get_year <- function(x, y){
  read.xlsx(x, sheet = y, startRow =1 , colNames = FALSE, rows = 1) %>% 
    rename(DES_jp = "X1") %>%
    mutate(FILE = x) %>%
    mutate(FILE = str_extract(FILE, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
    mutate(DES_jp = str_remove(DES_jp, "　※.+") )  %>%
    mutate(DES_jp = str_remove(DES_jp, "診療年月："))　%>%
    mutate(YEAR_str = str_extract(DES_jp, "[^年]+(?=年)")) %>%
    mutate(YEAR_end = str_extract(DES_jp, "(?<=～)[^年]+(?=年)")) %>%
    mutate(YEAR_str = convert_year(YEAR_str)) %>%
    mutate(YEAR_end = convert_year(YEAR_end))
    }
  
  # apply get_year function
  list_year <- map2(xlsx_path,
                     sheet_name, get_year)
    
  list_df <- map2(list_df, list_year, function(x, y){
    x %>% left_join(y, by = join_by(FILE == FILE))
  })
  
  
  # combine
  df <- list_df %>% list_rbind()
  
  return(df)

  }
```

```{r}
# for each folider, read the first two files, parse , combine and save
# x is the overall folder name (ext inj)
# y is the individual folder (dem prf)

save_df_dem_add <- function(x, y){
  xlsx <- list.files(paste0("../xlsx/", x, "/", y))
  
  #xlsx <- xlsx[1:2]
  
  from <- paste0("../xlsx/", x, "/", y, "/", xlsx)
  
  df <- map(from, get_data_dem_add) %>% list_rbind()
  
  
  # add category
  df <- df %>% 
    mutate(TYPE = x) %>%
    relocate(TYPE, .after = "FILE") %>%
    mutate(CAT = y) %>%
    relocate(CAT, .after = "TYPE")
  
  saveRDS(df, paste0("../rds/", x, "/", y,"/", "df_", x, "_", y, "_add"))
}
```


```{r}
save_df_dem_add("test", "dem")
```

```{r}
df_test_dem_add <- read_rds("../rds/test/dem/df_test_dem_add")
```

```{r}
df_test_dem_add %>% count(SHEET_jp)
```
```{r}
df_test_dem_add %>% count(YEAR_str)
```


# inj

```{r}
save_df_dem_reg("inj", "dem")
```


```{r}
df_test_dem_reg <- read_rds("../rds/test/dem/df_test_dem_reg")
```


```{r}
save_df_dem_add("inj", "dem")
```

```{r}
df_inj_dem_add <- read_rds("../rds/inj/dem/df_inj_dem_add")
```


# end of run

