---
title: "Pancreatic cacner"
output: html_document
date: "2026-04-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)

library(readxl)
library(openxlsx)
library(openxlsx2)

library(fpp3)

library(ggtext)
library(patchwork)
library(cowplot)
```


```{r}
# make df folder

#dir.create("../df/long", showWarnings = TRUE, recursive = FALSE, #mode = "0777")
```

```{r}
# make df folder

dir.create("../table", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
df_surg_dem <- readRDS("../df/dem/df_surg_dem_reg")
```

```{r}
#df_inj_dem <- readRDS("../df/dem/df_inj_dem_reg")
```

```{r}
df_inc_prf_long <- readRDS("../rds/cancer/df_inc_panc_long.RDS")
```


```{r}
df_surg_dem %>% count(YEAR_str)
```

```{r}
df_surg_dem %>% filter(is.na(TOTAL)) %>% nrow()
```


```{r}
df_surg_dem %>% count(SHEET, YEAR_str)
```

```{r}
df_surg_dem_total <- df_surg_dem %>%
  distinct(FILE, SHEET, PRO_code, .keep_all = TRUE) %>%
  rename(YEAR = "YEAR_str") %>%
  mutate(TOTAL = replace_na(TOTAL, 0))
  
```

```{r}
 df_surg_dem_total %>% 
  filter(str_detect(CLASS_code, "^K702|^K703")) %>% View()
```

```{r}
 df_surg_dem_total %>% 
  filter(str_detect(CLASS_code, "^K702|^K703")) %>% View()
```

```{r}
 df_surg_dem_total %>% 
  filter(str_detect(CLASS_code, "^K700|^K702|^K703")) %>% count(CLASS_code, CLASS_name)
```


```{r}
# 702 body and tail
# 703 head
# 704 total 全摘

df_panc <- df_surg_dem_total %>% 
  filter(str_detect(CLASS_code, "K700|^K702|^K703|^K704")) %>%
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        str_detect(PRO_name, "腹腔鏡") &  str_detect(PRO_name, "手術用支援機器") ~ "Robotic",
                        .default = "Open") ) %>%
  
  
  mutate(LOC = case_when(str_detect(PRO_name, "膵頭") ~ "Head",
                         str_detect(PRO_name, "膵体尾部") ~ "Distal",
                         str_detect(PRO_name, "全摘") ~ "Total",
                         CLASS_code == "K700" ~ "Middle",
                         CLASS_code %in% c("K700-2", "K700-3") ~ "Enucleation")) %>%
  mutate(TX = factor(TX, levels = c("Open", "Lap", "Robotic"))) %>%
  mutate(LOC = factor(LOC, levels = c("Head", "Distal", "Total", "Middle", "Enucleation")))
```



```{r}
df_panc_all <- df_panc %>%
              group_by(YEAR) %>%
              summarise(SUM = sum(TOTAL)) %>%
              mutate(TX = "All")
```


```{r}
df_panc_all <- df_panc_all %>%
  left_join(df_inc_prf_long %>%
              filter(PRF_jp == "全国" & SEX == "Total") %>%
              distinct(YEAR, .keep_all = TRUE) %>%
              select(YEAR, TOTAL),
            by = join_by(YEAR))
              
```

```{r}
lm_panc_tidy <- lm(SUM ~ TOTAL, data = df_panc_all) %>% tidy()

lm_panc_tidy
```

```{r}
lm_panc_glance <- lm(TOTAL ~ SUM, data = df_panc_all) %>% glance()

lm_panc_glance
```


```{r}
lm_panc_label <- lm_panc_tidy %>%
  mutate(term = str_remove_all(term, "\\(|\\)")) %>%
  select(term, estimate) %>%
  pivot_wider(names_from = term,
              values_from = estimate) %>%
  bind_cols(lm_panc_glance) %>%
  mutate(p = formatC(p.value, digits = 2, format = "fg", flag = "#")) %>%
  mutate(r_2 = formatC(adj.r.squared, digits = 2, format = "fg", flag = "#")) %>%
  mutate(alpha = round(Intercept)) %>%
  mutate(beta = formatC(TOTAL, digits = 2, format = "fg", flag = "#")) %>%
  mutate(label = paste0("*y* = ", beta, "*x* + ", alpha, "<br>",
                        "*p* = ", p, "<br>",
                        "*R*<sup>2</sup><sub>adj</sub> = ", r_2))

lm_panc_label
```

```{r}
df_panc_all %>%
  mutate(LOC = "All") %>%
  ggplot(aes(YEAR, TOTAL, group = LOC))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
  geom_smooth(method = "lm",
              se = FALSE,
              linewidth = 0.3,
              linetype = 2)+
  scale_y_continuous(limits = c(0, 50000),
                     labels = scales::label_comma()) +
  theme_classic()
```


```{r}
df_panc_all %>%
  ggplot(aes(TOTAL, SUM))+
  geom_point(size = 1)+
  geom_smooth(method = "lm")+
  geom_text(aes(label = YEAR),
                size = 2.8, colour = "black")+
  geom_richtext(data = lm_panc_label,
                aes(x = 40000 , y = 20000, label = label),
                hjust = 0, vjust = 1, size = 2.8, colour = "black",
                fill = NA, label.color = NA,
                label.padding = grid::unit(rep(0, 4), "pt")) +
  scale_x_continuous(limits = c(40000, 48000)) +
  scale_y_continuous(limits = c(15000, 20000)) +
  theme_classic()
```


```{r}
tsbl_panc_tx <- df_panc %>%
  group_by(YEAR, TX) %>%
  summarise(SUM = sum(TOTAL)) %>%
  bind_rows(df_panc %>%
              group_by(YEAR) %>%
              summarise(SUM = sum(TOTAL)) %>%
              mutate(TX = "All")) %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  mutate(TX = factor(TX, levels = c("All", "Open", "Lap", "Robotic"))) %>%
  ungroup() %>%
  as_tsibble(index = YEAR, key = TX)
```

```{r}
tsbl_panc_tx  %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance()
```

```{r}
tsbl_panc_tx  %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  tidy() %>%
  filter(term == "YEAR")
```

```{r}
tsbl_panc_tx   %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance() %>%
  left_join(tsbl_panc_tx  %>%
              model(tslm = TSLM(SUM ~ YEAR)) %>%
              tidy() %>%
              filter(term == "YEAR") %>%
              select(TX, estimate, std.error),
            by = join_by(TX)) %>%
  mutate(ci_low = estimate + std.error * qt(0.025, df = df.residual),
         ci_up = estimate + std.error * qt(1- 0.025, df = df.residual))
```



```{r}
p1_d1 <- tsbl_panc_tx  %>%
  filter(TX != "All") %>%
  
  mutate(label = case_when(YEAR %in% c(2014, 2023) ~ scales::comma(SUM),
                           .default = NA)) %>%
  
  mutate(hjust= case_when(YEAR == 2014 ~ 0,
                          YEAR == 2023 ~ 0.5,
                          .default = NA)) %>%
  
  mutate(vjust = case_when(YEAR == 2014 & TX == "Open" ~ 1,
                           YEAR %in% c(2014, 2023) ~ 0,
                           .default = NA)) %>%
  
  mutate(y = case_when(YEAR == 2023 & TX == "Lap"  ~ SUM + 16000/12.5*2,
                       YEAR == 2023 & TX == "Robotic"  ~ SUM + 16000/12.5*1,
                       YEAR == 2023 & TX == "Open" ~ SUM + 16000/15,
                       YEAR == 2014 & TX == "Open" ~ SUM - 16000/15,
                       YEAR == 2014 ~ SUM + 16000/15,
                       .default = NA)) %>%
  
  ggplot()+
  geom_line(aes(YEAR, SUM, colour = TX, group = TX),
            linewidth = 0.3)+
  geom_point(aes(YEAR, SUM, colour = TX),
             size = 1)+
  geom_text(aes(YEAR, y = y, label = label,
                hjust = hjust, vjust = vjust),
            size = 2.8, colour = "black" )+
  scale_colour_manual(values = c(
                                 "#1f77b4",
                                 "#d62728",
                                 "#bcbd22"),
                    name = "Pancreatectomy",
                    labels = c(
                               "Open",
                               "Laparoscopic",
                               "Robotic"))+
   scale_y_continuous(breaks = seq(0, 16000, 4000),
                     limits = c(0, 16000),
                     
                     label = scales::label_comma())+
  coord_cartesian(clip = "off")+
  labs(x = "Year",
       y = "Count (n)",
       tag = "d")+
      # title = "Pancreatomy")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.justification = c(0, 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "bottom",
        legend.background = element_blank(),
        plot.margin = margin(1, 5, 1, 0, unit = "mm"),
        legend.margin = margin(0, 0, 1, 0, "mm"),
        legend.box.spacing = unit(0, "mm"))

p1_d1 
```

```{r}
tsbl_panc_tx  %>%
  count(TX)
```

```{r}
tsbl_panc_tx  %>%
  as_tibble() %>%
  filter(TX != "All") %>%
  group_by(YEAR) %>%
  mutate(PCT = SUM/sum(SUM) * 100 ) %>%
  View()
```


```{r}
df_label_d2 <- tsbl_panc_tx  %>%
  as_tibble() %>%
  filter(TX != "All") %>%
  group_by(YEAR) %>%
  mutate(PCT = SUM/sum(SUM) * 100 ) %>%
  mutate(TX = factor(TX, levels = c("Lap", "Robotic", "Open"))) %>%
  arrange(TX) %>%
  mutate(CS = cumsum(PCT)) %>%
  mutate(HT = CS - PCT* 1/2) %>%
  mutate(label = case_when( TX == "Open" |
                              TX == "Lap" & YEAR >= 2018 |
                              TX == "Robotic" & YEAR == 2023 ~ round(PCT),
                            .default = NA)) %>%
  
  mutate(vjust = 0.5) %>%
  
  mutate(y = case_when(TX == "Open" ~ 50,
                       TX == "Lap" ~ 5,
                       TX == "Robotic" ~ HT,
                       .default = NA)) %>%
  
  mutate(colour = case_when(TX %in% c("Open", "Lap") ~ "a",
                            TX == "Robotic" ~ "b"))

df_label_d2
```


```{r}
p1_d2 <- tsbl_panc_tx  %>%
  as_tibble() %>%
  filter(TX != "All") %>%
  group_by(YEAR) %>%
  mutate(PCT = SUM/sum(SUM) * 100 ) %>%
  mutate(TX = factor(TX, levels = c("Open", "Robotic", "Lap"))) %>%
  
  ggplot()+
  geom_col(aes(YEAR, PCT, fill = TX),
           width = 0.75, position = "stack")+
  geom_text(data = df_label_d2,
            aes(x = YEAR, y = y,
                label = label,
                vjust = vjust,
                colour = colour),
            hjust = 0.5,
            size = 2.8,
            inherit.aes = FALSE)+
  scale_colour_manual(values = c("white", "black"))+
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#d62728"),
                    name = "Pancreatectomy",
                    breaks = c("Open", "Robotic", "Lap"),
                    labels = c(
                               "Open",
                               "Laparoscopic",
                               "Robotic"))+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 100, 25)) +
  labs(x = "Year",
       y = "Proportion (%)")+
  theme_classic()+
  theme(
        axis.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.text = element_text(size = 8, colour = "black", hjust = 0.5),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
         plot.margin = margin(1, 0, 1, 5, unit = "mm"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "none")

p1_d2
```



```{r}
tsbl_panc_loc <- df_panc %>%
  group_by(YEAR, LOC) %>%
  summarise(SUM = sum(TOTAL)) %>%
  bind_rows(df_panc %>%
              group_by(YEAR) %>%
              summarise(SUM = sum(TOTAL)) %>%
              mutate(LOC = "All")) %>%
  mutate(LOC = factor(LOC, levels = c("All",
                                      "Head",
                                      "Distal",
                                      "Total",
                                      "Middle",
                                      "Enucleation"))) %>%
  mutate(YEAR = as.numeric(YEAR))  %>%
  ungroup() %>%
  as_tsibble(key = LOC, index = YEAR)
```

```{r}
tsbl_panc_loc
```


```{r}
label_panc_loc <- tsbl_panc_loc %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance()
```

```{r}
lm_panc_loc <- tsbl_panc_loc %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  tidy()

lm_panc_loc 
```


```{r}

p1_a1 <- tsbl_panc_loc %>%
  mutate(label = case_when(YEAR %in% c(2014, 2023) & !(LOC %in% c("Middle", "Enucleation")  )~ scales::comma(SUM),
                           .default = NA)) %>%

  mutate(hjust = case_when(YEAR == 2014 ~ 0,
                       YEAR == 2023 ~ 0.5,
                       .default = NA)) %>%
  
  mutate(y = case_when(YEAR %in% c(2014, 2023) ~ SUM + 20000/15,
                           .default = NA)) %>%
  
  ggplot()+
  geom_line(aes(YEAR, SUM, group = LOC, colour = LOC), linewidth = 0.3)+
  geom_point(aes(YEAR, SUM, colour = LOC), size = 1)+
  geom_text(aes(x = YEAR, y = y, hjust = hjust, label = label),
            vjust = 0, size = 2.8, colour = "black")+
  scale_colour_manual(values = c("#8c564b",
                                 "#1f77b4",
                                 "#d62728",
                                 "#bcbd22",
                                 "#e377c2",
                                 "#17becf"),
                          labels = c("All",
                                     "Head",
                                     "Distal",
                                     "Total",
                                     "Middle",
                                     "Enucleation"),
                    name = "Pancreatectomy")+
  scale_y_continuous(breaks = seq(0, 20000, 5000),
                     limits = c(0, 20000),
                     label = scales::label_comma())+
  guides(color = guide_legend(nrow = 1) )+
  coord_cartesian(clip = "off")+
  labs(x = "Year",
       y = "Count (n)",
       tag = "a")+
       #title = "Pancreatomy")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.justification = c(0, 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "bottom",
        legend.background = element_blank(),
        plot.margin = margin(1, 5, 1, 0, unit = "mm"),
        legend.margin = margin(0, 0, 1, 0, "mm"),
        legend.box.spacing = unit(0, "mm"))

p1_a1
```


```{r}
# proportion

p1_a2 <- tsbl_panc_loc %>%
  as_tibble() %>%
  filter(LOC != "All") %>%
  mutate(LOC = factor(LOC,
                      levels = c("Enucleation",
                                 "Middle",
                                 "Total",
                                 "Distal",
                                 "Head"))) %>%
  group_by(YEAR) %>%
  mutate(ALL = sum(SUM)) %>%
  mutate(PCT = SUM/ALL * 100) %>%
  mutate(label = round(PCT)) %>%
  mutate(label = na_if(label, LOC == "Total")) %>%
  mutate(y = case_when(LOC == "Head" ~ 30,
                       LOC == "Distal" ~80,
                       .default = NA)) %>%
  ggplot(aes(YEAR, PCT, fill = LOC))+
  geom_col(width = 0.75)+
  scale_fill_manual(values = c("#17becf",
                                 "#e377c2",
                                 "#bcbd22",
                                "#d62728",
                                 "#1f77b4"),
                    name = "Pancreatectomy")+
  geom_text(aes(y = y, label = label),
            size = 2.8, colour ="white")+
  labs(x = "Year",
       y = "Proportion (%)")+
  scale_y_continuous(expand  = c(0, 0),
                     breaks = seq(0, 100, 25))+
  theme_classic()+
   theme(# plot.tag = element_text(size = 12, colour = "black", face = "bold", hjust = 0.5),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(1, 0, 1, 5, unit = "mm"),
        legend.position = "none")

p1_a2
```


```{r}
tsbl_panc <- df_panc %>%
  group_by(YEAR, TX, LOC) %>%
  summarise(SUM = sum(TOTAL)) %>%
  ungroup() %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  as_tsibble(index = YEAR, key = c(TX, LOC))
  
tsbl_panc 
```

```{r}
p1_b1 <- tsbl_panc %>%
  filter(LOC == "Head") %>%
  mutate(label = case_when(YEAR %in% c(2014, 2023) ~ scales::comma(SUM),
                           .default = NA)) %>%
  
  mutate(hjust = case_when(YEAR == 2014 ~ 0,
                           YEAR == 2023 ~ 0.5,
                           .default = NA)) %>%
  
  mutate(vjust = case_when(YEAR == 2014 ~ 0,
                           YEAR == 2023 ~ 0,
                           .default = NA)) %>%
  
  mutate(y = case_when(vjust == 0 & TX %in% c("Lap", "Open") ~ SUM + 12000/15,
                       vjust == 0 & TX == "Robotic" ~ SUM + 12000/12.5 * 2,
                       vjust == 1 ~ SUM - 12000/15,
                       .default = NA)) %>%
  
  ggplot() +
  geom_line(aes(YEAR, SUM, colour = TX, group = TX),
            linewidth = 0.3) +
  geom_point(aes(YEAR, SUM, colour = TX),
             size = 1)+
  geom_text(aes(x = YEAR, y = y, label = label,
                hjust = hjust, vjust = vjust),
            size = 2.8, colour = "black")+
  scale_colour_manual(values = c( "#2ca02c",
                                 "#ff7f0e",
                                 "#9467bd"),
                    name = "Pancreatic head",
                    labels = c(
                               "Open",
                               "Laparoscopic",
                               "Robotic"))+
    scale_y_continuous(limits = c(0, 12000),
                     breaks = seq(0, 12000, 3000),
                     labels = scales::label_comma())+
  coord_cartesian(clip = "off")+
  labs(x = "Year",
       y = "Count (n)",
       tag = "b")+
       #title = "Pancreatomy")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.justification = c(0, 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "bottom",
        legend.background = element_blank(),
        plot.margin = margin(1, 5, 1, 0, unit = "mm"),
        legend.margin = margin(0, 0, 1, 0, "mm"),
        legend.box.spacing = unit(0, "mm"))

p1_b1 
```


```{r}
p1_b2 <- tsbl_panc %>%
  as_tibble() %>%
  filter(LOC == "Head") %>%
  group_by(YEAR) %>%
  mutate(TOTAL = sum(SUM)) %>%
  mutate(PCT = SUM/TOTAL * 100) %>%
  mutate(TX = factor(TX, levels = c("Robotic", "Lap", "Open"))) %>%
  mutate(label = case_when(TX == "Open" ~ round(PCT),
                           .default = NA)) %>%
  mutate(y =  case_when(TX == "Open" ~ 50,
                           .default = NA)) %>%
  ggplot(aes(YEAR, PCT, fill = TX))+
  geom_col(width = 0.75, position = "stack")+
  geom_text(aes(y = y, label = label),
            size= 2.8, colour = "white")+
   scale_fill_manual(values = c(
                                 "#2ca02c",
                                 "#ff7f0e",
                                 "#9467bd"),
                    name = "Pancreatic\nhead cancer",
                    labels = c(
                               "Open",
                               "Laparoscopic",
                               "Robotic"),
                    breaks = c("Open",
                               "Lap",
                               "Robotic"))+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 100, 25)) +
  labs(x = "Year",
       y = "Proportion (%)")+
      # tag = "E")+
       #title = "Pancreatomy")+
  theme_classic()+
  theme(# plot.tag = element_text(size = 12, colour = "black", face = "bold", hjust = 0.5),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
         plot.margin = margin(1, 0, 1, 5, unit = "mm"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "none")


p1_b2
```



```{r}
p1_c1 <- tsbl_panc %>%
  filter(LOC == "Distal") %>%
  mutate(label = case_when(YEAR %in% c(2014, 2023) ~ scales::comma(SUM),
                           .default = NA)) %>%
  
  mutate(hjust = case_when(YEAR == 2014 ~ 0,
                           YEAR == 2023 ~ 0.5,
                           .default = NA)) %>%
  
  mutate(vjust = case_when(YEAR == 2014 & TX == "Open" ~ 1,
                           YEAR == 2014 & TX == "Lap" ~ 0,
                           .default = 0)) %>%
  
  mutate(y  = case_when(vjust == 0 ~ SUM + 5000/15,
                        vjust == 1 ~ SUM - 5000/15,
                        .default = NA)) %>%
  
  ggplot() +
  geom_line(aes(YEAR, SUM, colour = TX, group = TX),
            linewidth = 0.3) +
  geom_point(aes(YEAR, SUM, colour = TX),
             size = 1)+
  geom_text(aes(x = YEAR, y = y, label = label,
                hjust = hjust, vjust = vjust),
            size = 2.8, colour = "black") +
  scale_colour_manual(values = c( "#2ca02c",
                                 "#ff7f0e",
                                 "#9467bd"),
                    name = "Distal pancreas",
                    labels = c(
                               "Open",
                               "Laparoscopic",
                               "Robotic"))+
  scale_y_continuous(limits = c(0, 5000),
                     breaks = seq(0, 5000, 1000),
                     labels = scales::label_comma())+
  coord_cartesian(clip = "off")+
  labs(x = "Year",
       y = "Count (n)",
       tag = "c")+
       #title = "Pancreatomy")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black", hjust = 0.5),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.justification = c(0, 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "bottom",
        legend.background = element_blank(),
        legend.margin = margin(0, 0, 1, 0, unit = "mm"),
        plot.margin = margin(1, 5, 1, 0, unit = "mm"),
        legend.box.spacing = unit(0, "mm"))

p1_c1
```


```{r}
df_label_c2 <- tsbl_panc %>%
  as_tibble() %>%
  filter(LOC == "Distal") %>%
  group_by(YEAR) %>%
  mutate(TOTAL = sum(SUM)) %>%
  mutate(PCT = SUM/TOTAL * 100) %>%
  mutate(TX = factor(TX, levels = c("Open", "Lap", "Robotic"))) %>% 
  mutate(CS = cumsum(PCT)) %>%
  mutate(HT = CS - PCT/2) %>%
  
  mutate(label = case_when(TX == "Open"  |
                       TX == "Lap" & YEAR <= 2019 |
                       TX == "Lap" & YEAR >= 2020 |
                       TX == "Robotic" & YEAR == 2023 ~ round(PCT),
                       .default = NA)) %>%
  
  mutate(y = case_when(TX == "Open" ~ 25,
                       TX == "Lap" & YEAR <= 2019 ~ 95,
                       TX == "Lap" & YEAR >= 2020 ~ HT,
                       TX == "Robotic" & YEAR == 2023 ~ 95)) %>%
  mutate(vjust = case_when(TX == "Open" ~ 0.5,
                       TX == "Lap" & YEAR <= 2019 ~ 1,
                       TX == "Lap" & YEAR >= 2020 ~ 0.5,
                       TX == "Robotic" & YEAR == 2023 ~ 1,
                       .default = NA)) %>%
  mutate(colour = case_when(TX == "Lap" ~ "a",
                            .default = "b")) %>%
  mutate(TX = factor(TX, levels = c("Robotic", "Lap", "Open")))

df_label_c2 
```


```{r}
p1_c2 <- tsbl_panc %>%
  as_tibble() %>%
  filter(LOC == "Distal") %>%
  group_by(YEAR) %>%
  mutate(TOTAL = sum(SUM)) %>%
  mutate(PCT = SUM/TOTAL * 100) %>%
  mutate(TX = factor(TX, levels = c("Robotic", "Lap", "Open"))) %>%
  
  ggplot(aes(YEAR, PCT, fill = TX))+
  geom_col(width = 0.75, position = "stack")+
  
  geom_text(data = df_label_c2,
            aes(x = YEAR, y =  y,
                label = label,
                vjust = vjust, colour = colour),
            size = 2.8,
            inherit.aes = FALSE) +
  scale_colour_manual(values = c( "black", "white"))+
   scale_fill_manual(values = c(
                                "#2ca02c",
                                 "#ff7f0e",
                                 "#9467bd"),
                    name = "Distal pancreas",
                    labels = c(
                               "Open",
                               "Laparoscopic",
                               "Robotic"),
                    breaks = c("Open",
                               "Lap",
                               "Robotic"))+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 100, 25))+
  labs(x = "Year",
       y = "Proportion (%)")+
       #title = "Pancreatomy")+
  theme_classic()+
  theme(# plot.tag = element_text(size = 12, colour = "black", face = "bold", hjust = 0.5),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
         plot.margin = margin(1, 0, 1, 5, unit = "mm"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "none")


p1_c2
```


```{r}
p1 <- p1_a1 + p1_a2 +
  p1_b1+
  patchwork::free(p1_b2, type = "label") + 
  p1_c1 + 
  patchwork::free(p1_c2, type = "label") + 
  p1_d1 + 
  patchwork::free(p1_d2, type = "label") + 
  plot_layout(design = "
  AB
  CD
  EF
  GH")

p1
```

```{r}
ggsave("../figure/Fig1.pdf", units = "mm", height = 234, width = 174)
```



```{r}
tsbl_panc_tx %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance()
```


```{r}
tsbl_panc %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance()
```

```{r}
tsbl_panc_loc %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance()
```

```{r}
# t1 loc
# t2 head
# t3 distal
# t4 open/lap/robotic

```

```{r}
t1_1 <- tsbl_panc_loc %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance()

t1_1
```


```{r}
t1_2 <- tsbl_panc %>%
  filter(LOC == "Head") %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance()

t1_2 
```

```{r}
t1_3 <- tsbl_panc %>%
  filter(LOC == "Distal") %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance()

t1_3 
```

```{r}
t1_4 <- tsbl_panc_tx %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance()

t1_4
```

```{r}
tslm_panc_1 <- tsbl_panc_loc %>% mutate(TX = "All") %>% 
  mutate(TX = "All") %>%
  update_tsibble(key = c(TX, LOC)) %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  mutate(TX = "All",
         TAG = "a")

tslm_panc_1
```


```{r}
tslm_panc_2 <- tsbl_panc %>% filter(LOC == "Head") %>% mutate(NO = "b") %>% 
   group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR))%>%
  mutate(TAG = "b")
  
tslm_panc_2 
```

```{r}
tslm_panc_3 <- tsbl_panc %>% filter(LOC == "Distal") %>% mutate(NO = "c") %>%   group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR))  %>%
  mutate(TAG = "c")

tslm_panc_3 
```


```{r}
tslm_panc_4 <- tsbl_panc_tx %>% mutate(LOC = "All") %>%
  filter(TX != "All") %>%
  update_tsibble(key = c(TX, LOC)) %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  mutate(TAG = "d",
         LOC = "All")

tslm_panc_4
```


```{r}
tslm_panc_comb <- tslm_panc_1 %>%
  bind_rows(tslm_panc_2) %>%
  bind_rows(tslm_panc_3) %>%
  bind_rows(tslm_panc_4) 
```


```{r}
df_tslm_1 <- tslm_panc_comb %>%
  glance() %>%
  mutate(ID = paste0(LOC, "_", TX)) %>%
  select(LOC, TX, .model, r_squared, adj_r_squared, p_value, df.residual, ID)

df_tslm_1
```

```{r}
df_tslm_2 <-  tslm_panc_comb %>%
  tidy() %>%
  filter(term == "YEAR") %>%
  mutate(ID = paste0(LOC, "_", TX)) %>%
  select(estimate, std.error, p.value, ID)

df_tslm_2
```


```{r}
df_tslm <- df_tslm_1 %>%
  left_join(df_tslm_2,
            by = join_by(ID))

df_tslm %>% View()
```


```{r}
# adjusted R2, 95% CI

df_tslm <- df_tslm %>%
  
  mutate(r_adj = formatC(adj_r_squared, digits = 2, format = "fg", flag = "#")) %>%
  
  mutate(beta = formatC(estimate, digits = 3, format = "fg", flag = "#")) %>%
  mutate(beta = str_trim(beta, side = "both")) %>%
  mutate(beta = case_when(str_detect(beta, "\\.$") & str_length(beta) == 3  ~ paste0(beta, "0"),
         .default = beta)) %>%
  
  mutate(beta = str_remove(beta, "\\.$")) %>%
  mutate(beta = str_trim(beta, side = "both")) %>%
  
  mutate(ci_low = estimate - std.error * qt(0.95, df = df.residual),
         ci_up = estimate + std.error * qt(0.95, df = df.residual)) %>%
  mutate(across(starts_with("ci"), ~ formatC(.x, digits = 3, format = "fg"))) %>%
  mutate(across(starts_with("ci"), ~ str_trim(.x, side = "both"))) %>%
  mutate(ci = paste0("[", ci_low, ", ", ci_up, "]"))

df_tslm
```

```{r}
df_tslm <- df_tslm %>%
  mutate(across(c(beta, ci, r_adj), ~ str_replace_all(.x, "-", "−")))
```


```{r}
get_exp <- function(x){

  # if na return ""
  
  if(is.nan(x) | x > 0.001){
    return("")
  }
  
  else {
    
    p <- formatC(x, digits = 2, format = "e", flag = "#")
    
    ex <- p %>% str_extract("(?<=e).+") %>% str_remove_all("(?<=\\-)0+") %>%
      str_replace_all("-", "−")
    
    return(ex)
    }
}

get_expv <- Vectorize(get_exp)
```

```{r}
get_num <- function(x){
  
  if (is.nan(x)){
      return("NA")
    }
  
  else if (x > 0.001) {
    p <- formatC(x, digits = 2, format = "fg", flag = "#")
    
    return(p)
  }
  
  else{
    p <- formatC(x, digits = 1, format = "e", flag = "#")
    
    num <- p %>% str_extract(".+(?=e)")
    
    num <- str_c(num, "×10")
      
    return(num)
  }
}

get_numv <- Vectorize(get_num)
```

```{r}
symbol_p <- function(x){
  if (is.nan(x)){
    return("")
  }
  else if (x < 0.001){
    return("***")
    }
  else if (x < 0.01){
    return("**")
  }
  else if (x < 0.05){
    return("*")
  }
  else {
    return("")
  }
}

symbol_pv <- Vectorize(symbol_p)
```

```{r}
#t1_mod <- 

wb_1 <- df_tslm %>%
  mutate(p_exp = get_expv(p_value)) %>%
  mutate(p_num = get_numv(p_value)) %>%
  mutate(p = purrr::map2(p_num, p_exp, function(x, y){
    c(fmt_txt(x), fmt_txt(y, vert_align = "superscript")) 
    }) ) %>%
  mutate(p_symbol = symbol_pv(p_value))

```

```{r}
wb_1 <- wb_1 %>%
  mutate(TX = str_replace(TX, "All", ""))
```


```{r}
wb_1 <- wb_1 %>%
#  mutate(LOC = str_replace(LOC, "All", "All "))
  select(LOC, TX, beta, ci, p, p_symbol, r_adj)


wb_workbook() %>%
  wb_add_worksheet("Sheet1") %>%
  wb_add_data(x = wb_1 ) %>%
  wb_save("../table/Table1.xlsx")
```

